optimal nettop so that we avoid scan the whole /proc
alibaba/kubeskoop pull request #139
Opened 2024-01-02 03:04 UTC by jzwlqx

to achieve this goal, we use local cri interface to get required pod information, such as netns, ip, pids.

cri v1 has GetContainerEvents methon that can be used to watch container change events, once container changed, we can call ContainerStatus to get container detail info. Unfortunately there is a bug in containerd: only one caller of GetContainerEvents is supported. So now we have to list containers periodically to get caontiner info.

cri interface return only root pid for every container, so we read cgroup tasks to get all pids of pods.

2024-01-09 03:43 UTC, BSWANG requested changes

2024-01-09 03:43 UTC, BSWANG commented on pkg/exporter/nettop/cache.go
>  	cacheDone := make(chan struct{})
cacheDone not close

2024-01-10 03:32 UTC, Lyt99 approved these changes

2024-01-10 07:43 UTC, BSWANG approved these changes

2024-01-10 07:43 UTC, merged