feat(metrics): helm add additionalLabels
alibaba/kubeskoop pull request #277
Opened 2024-05-14 07:22 UTC by halleystar

2024-05-14 07:59 UTC, Lyt99 requested changes

2024-05-14 07:59 UTC, Lyt99 commented on deploy/helm/templates/configmap.yaml
> +      {{- toYaml .Values.config.additionalLabels | nindent 8 }}
Cloud you please add some examples to `values.yaml`?

2024-05-14 08:01 UTC, Lyt99 commented
Hi, thanks for your contribution!

It looks good to me, and it could be better if you provide examples for this configuration in `values.yaml`, thank you!

2024-05-14 08:09 UTC, halleystar commented
I've added an example in values.yaml

2024-05-15 01:55 UTC, Lyt99 approved these changes

2024-05-16 02:34 UTC, merged